### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Tricoco** [cq0907/INIF#1]
Could you  please provide an example of a dataset? The link provided to access the dataset is no longer valid

**Comment by cq0907** [comment]
> Could you please provide an example of a dataset? The link provided to access the dataset is no longer valid

You can download through this link(https://drive.google.com/drive/folders/18wX4LWWee3yo41UIzPpaszFhWuFSPaOI?usp=drive_link). I hope this helps!

**Comment by Tricoco** [comment]
Thanks for your reply，but this link still requires access when using my own account

**Comment by cq0907** [comment]
> Thanks for your reply，but this link still requires access when using my own account

Sorry, I forgot to set permissions (https://drive.google.com/drive/folders/18wX4LWWee3yo41UIzPpaszFhWuFSPaOI?usp=sharing).

**Comment by Tricoco** [comment]
Thanks, I can now download the data

**Comment by Tricoco** [comment]
how can I get the file in the code mlp8256_multiscale_450_512_grad106.py line 385 :
sample_points = np.load('./data/2D/{}.npy'.format(sample_points_name))
I can't find a script to get the sample_points.npy in this repo

**Comment by cq0907** [comment]
> how can I get the file in the code mlp8256_multiscale_450_512_grad106.py line 385 : sample_points = np.load('./data/2D/{}.npy'.format(sample_points_name)) I can't find a script to get the sample_points.npy in this repo

I have uploaded the corresponding .npy file to the link (https://drive.google.com/drive/folders/18wX4LWWee3yo41UIzPpaszFhWuFSPaOI?usp=sharing), It is some points sampled in advance in space to facilitate data loading.
